config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :api do
    resources :callbacks, only: [] do
      collection do
        post :success, :fail
      end
    end
  end

  authenticated :user do
    resources  :login do
      member do
        post :refresh_accounts
        post :reconnect
        post :refresh
      end
      resources :accounts, shallow: true, only: :show
    end
    resources :token
  end

  root "welcome#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :salt_transactions, primary_key: :salt_id, dependent: :destroy, class_name: "Transaction"
  belongs_to :login, primary_key: :salt_id
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user
end

app/models/login.rb
class Login < ActiveRecord::Base
  has_many :accounts, primary_key: :salt_id, dependent: :destroy
end

app/models/token.rb
class Token < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many     :logins, primary_key: :salt_id, foreign_key: :customer_id, dependent: :destroy
  has_many     :accounts, through: :logins
  has_many     :tokens, primary_key: :salt_id, foreign_key: :customer_id, dependent: :destroy
  after_create :create_customer

private

  def create_customer
    customer = Saltedge::Client.new.create_customer(email)
    self.update_attributes(salt_id: customer["id"], salt_secret: customer["secret"])
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @transactions = current_account.salt_transactions
  end

private
  def current_account
    @current_account ||= current_user.accounts.find(params[:id])
  end
end

app/controllers/api/callbacks_controller.rb
class Api::CallbacksController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_filter :authenticate_user!

  def success
    puts params

    login_hash = Saltedge::Client.new.show_login(params[:data][:login_id])

    puts login_hash

    login_hash["salt_id"] = login_hash.delete("id")
    login = Login.find_or_create_by(salt_id: login_hash["salt_id"])
    login.update_attributes(login_hash)

    accounts = Saltedge::Client.new.get_accounts(login)
    save_fresh_accounts(accounts)

    transactions = Saltedge::Client.new.get_transactions(login)
    save_fresh_transactions(transactions)

    render :nothing => true
  end

  def save_fresh_accounts(accounts)
    accounts.each do |account|
      account["salt_id"] = account.delete("id")
      db_account = Account.find_or_create_by(salt_id: account["salt_id"])
      db_account.update_attributes(account)
    end
  end

  def save_fresh_transactions(transactions)
    transactions.each do |transaction|
      transaction["salt_id"] = transaction.delete("id")
      db_transaction = Transaction.find_or_create_by(salt_id: transaction["salt_id"])
      db_transaction.update_attributes(transaction)
    end
  end

  def fail
    puts params

    login_hash = Saltedge::Client.new.show_login(params[:data][:login_id])
    puts "BEFORE LOGIN_HASH"
    puts login_hash

    login_hash["salt_id"] = login_hash.delete("id")
    login = Login.find_or_create_by(salt_id: login_hash["salt_id"])
    login.update_attributes(login_hash)
    login.update_attributes(
      :fail_message => login_hash["last_attempt"]["fail_message"],
      :fail_error_class => login_hash["last_attempt"]["fail_error_class"]
    )
    puts "LOGIN WAS CREATED"

    render :nothing => true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
    if params[:login_id]
      login_hash = Saltedge::Client.new.show_login(params[:login_id])
      login_hash["salt_id"] = login_hash.delete("id")
      login = Login.find_or_create_by(salt_id: login_hash["salt_id"])
      login.update_attributes(login_hash)
    end

    @logins = current_user.logins
  end

  def show
    @accounts = current_login.accounts
  end

  def create_token
    token = Saltedge::Client.new.create_token(token_params)
    redirect_to token["connect_url"]
  end

  def reconnect
    token = Saltedge::Client.new.reconnect_token(current_login)
    redirect_to token["connect_url"]
  end

  def refresh
    token = Saltedge::Client.new.refresh_token(current_login)
    redirect_to token["connect_url"]
  end

  def create
    login = Saltedge::Client.new.create_login(login_params)
    login["salt_id"] = login.delete("id")
    Login.create(login)
    redirect_to login_index_path
  end

  def update
    fresh_login = Saltedge::Client.new.refresh_login(current_login)
    fresh_login["salt_id"] = fresh_login.delete("id")
    current_login.update_attributes(fresh_login)
    redirect_to login_index_path
  end

  def destroy
    Saltedge::Client.new.destroy_login(current_login)
    current_login.delete
    redirect_to login_index_path
  end

  def refresh_accounts
    accounts = Saltedge::Client.new.get_accounts(current_login)
    save_fresh_accounts(accounts)
    transactions = Saltedge::Client.new.get_transactions(current_login)
    save_fresh_transactions(transactions)
    redirect_to login_index_path
  end


private
  def save_fresh_accounts(accounts)
    accounts.each do |account|
      account["salt_id"] = account.delete("id")
      db_account = Account.find_or_create_by(salt_id: account["salt_id"])
      db_account.update_attributes(account)
    end
  end

  def save_fresh_transactions(transactions)
    transactions.each do |transaction|
      transaction["salt_id"] = transaction.delete("id")
      db_transaction = Transaction.find_or_create_by(salt_id: transaction["salt_id"])
      db_transaction.update_attributes(transaction)
    end
  end

  def current_login
    @current_login ||= current_user.logins.find(params[:id])
  end

  def login_params
    {
      customer_id: current_user.salt_id,
      username: params["username"],
      password: params["password"],
      provider_code: params["provider_code"],
      country_code: params["country_code"]
    }
  end

  def token_params
    {
      customer_id: current_user.salt_id,
      return_login_id: true
    }
  end
end

app/controllers/token_controller.rb
class TokenController < ApplicationController

  def index
    @tokens = current_user.tokens
  end

  def create
    token = Saltedge::Client.new.create_token(token_params)
    token["salt_id"] = current_user.salt_id
    Token.create(token)
    redirect_to token["connect_url"]
  end

  def token_params
    {
      customer_id: current_user.salt_id,
    }
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_be_refreshed?(login)
    return true if login.next_refresh_possible_at.blank?
    Time.now > login.next_refresh_possible_at
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
  <li class="breadcrumb-item"><%= link_to "All logins", login_index_path %></li>
  <li class="breadcrumb-item"><%= link_to @current_account.login.provider_name, login_path(@current_account.login) %></li>
  <li class="breadcrumb-item active"><%= @current_account.name %></li>
</ol>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Currency code</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description%></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency_code %></td>
        <td><%= transaction.made_on %></td>
        <td><%= transaction.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
  <li class="breadcrumb-item active">All logins</li>
</ol>
<table class="table">
  <thead>
    <tr>
      <th>Bank name</th>
      <th>Actions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= link_to login.provider_name, login_path(login) %></td>
        <td><%= button_to "Reconnect", reconnect_login_path(login), class: "btn" %></td>
        <% if login.next_refresh_possible_at && login.next_refresh_possible_at.utc > Time.now.utc %>
          <td>
            <%= button_to "Refresh", refresh_login_path(login), disabled: true, class: "btn" %>
            <%= "Login can be refreshed in " + distance_of_time_in_words(login.next_refresh_possible_at, Time.now.utc) %>
          </td>
        <% elsif login.fail_message == "Invalid password." %>
          <td>
            <%= button_to "Refresh", refresh_login_path(login), disabled: true, class: "btn" %>
            <%= login.fail_message %>
          </td>
        <% else %>
          <td><%= button_to "Refresh", refresh_login_path(login), class: "btn" %></td>
        <% end %>

        <td><%= button_to "delete", login, method: :delete, class: "btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/login/new.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-4">
    <h2>Create new login</h2>
    <%= bootstrap_form_tag url: '/login' do |f| %>
      <%= f.text_field :provider_code %>
      <%= f.text_field :country_code %>
      <%= f.text_field :username %>
      <%= f.password_field :password %>
      <%= f.submit 'Create' %>
    <% end %>
  </div>
</div>

app/views/login/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
  <li class="breadcrumb-item"><%= link_to "All logins", login_index_path %></li>
  <li class="breadcrumb-item active"><%= @current_login.provider_name %></li>
</ol>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>balance</th>
      <th>Currency code</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |acc| %>
      <tr>
        <td><%= link_to acc.name, account_path(acc)  %></td>
        <td><%= acc.balance %></td>
        <td><%= acc.currency_code %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-4">
    <h3><%= link_to "Show all accounts",  login_index_path %></h3>

    <h4>Create new login:</h4>

    <%= link_to "Create login",  new_login_path, class: "btn btn-success" %>

    <h4>Create new token:</h4>

    <%= bootstrap_form_tag url: '/token' do |f| %>
      <%= f.submit 'Create token' %>
    <% end %>
  </div>
</div>